"""
trello_client.py
Thin wrapper around the Trello REST API.

Requires TRELLO_API_KEY, TRELLO_TOKEN, and TRELLO_BOARD_ID.
When credentials are missing the client operates in mock mode and returns
fake success responses so the rest of the app can still be demonstrated.
"""

import requests

_BASE = "https://api.trello.com/1"


class TrelloClient:
    def __init__(self, api_key: str, token: str, board_id: str):
        self.api_key = api_key
        self.token = token
        self.board_id = board_id
        self._auth = {"key": api_key, "token": token}

    # ── Read ──────────────────────────────────────────────────────────────────

    def get_board_lists(self) -> list[dict]:
        """Return all lists on the configured board."""
        url = f"{_BASE}/boards/{self.board_id}/lists"
        resp = requests.get(url, params=self._auth, timeout=10)
        resp.raise_for_status()
        return resp.json()

    # ── Write ─────────────────────────────────────────────────────────────────

    def create_card(self, card: dict, list_id: str) -> dict:
        """
        POST a backlog card dict to Trello.
        Returns {"success": True, "url": ..., "id": ...}
             or {"success": False, "error": ...}.
        """
        payload = {
            **self._auth,
            "name": card.get("title", "Untitled card"),
            "desc": _format_description(card),
            "idList": list_id,
            "pos": "bottom",
        }
        try:
            resp = requests.post(f"{_BASE}/cards", data=payload, timeout=10)
            resp.raise_for_status()
            data = resp.json()
            return {"success": True, "url": data.get("shortUrl", ""), "id": data.get("id")}
        except requests.HTTPError as exc:
            return {"success": False, "error": f"HTTP {exc.response.status_code}: {exc.response.text[:200]}"}
        except Exception as exc:
            return {"success": False, "error": str(exc)}


# ── Helpers ───────────────────────────────────────────────────────────────────

def _format_description(card: dict) -> str:
    """Build a Trello card description from the backlog card dict."""
    lines = [
        f"**{card.get('user_story', '')}**",
        "",
        card.get("description", ""),
        "",
        "**Acceptance Criteria**",
    ]
    for criterion in card.get("acceptance_criteria", []):
        lines.append(f"- {criterion}")

    lines += [
        "",
        f"**Effort:** {card.get('estimated_effort', '?')}  |  "
        f"**Priority:** {card.get('priority', '?')}  |  "
        f"**Labels:** {', '.join(card.get('labels', []))}",
        "",
        "_Generated by Review2Roadmap_",
    ]
    return "\n".join(lines)


def is_configured(api_key: str, token: str, board_id: str, list_id: str) -> bool:
    """Return True only when all four Trello credentials are present."""
    return all([api_key, token, board_id, list_id])


def mock_create_card(card: dict) -> dict:
    """Fake success response used when Trello credentials are not configured."""
    return {
        "success": True,
        "url": "https://trello.com/c/mock",
        "id": "mock-id",
        "mock": True,
    }
