"""
trello_client.py
Simple Trello REST API client for Review2Roadmap.

Credentials are read from st.secrets (Streamlit Cloud) first, then from
environment variables. They are never hardcoded, printed, or logged.
All methods return structured dicts and never raise — callers can check
the 'error' key without wrapping in try/except.
"""

import os
import requests

_BASE = "https://api.trello.com/1"


# ── Credential helpers ────────────────────────────────────────────────────────

def _get_credentials() -> tuple[str, str]:
    """
    Read TRELLO_API_KEY and TRELLO_TOKEN from st.secrets (Streamlit Cloud)
    then fall back to environment variables.
    Returns ("", "") if neither source has both values.
    Credentials are passed directly to requests — never printed or logged.
    """
    try:
        import streamlit as st
        key   = st.secrets.get("TRELLO_API_KEY", "")
        token = st.secrets.get("TRELLO_TOKEN", "")
        if key and token:
            return key, token
    except Exception:
        pass  # Not in a Streamlit context, or secrets.toml not configured
    return (
        os.environ.get("TRELLO_API_KEY", ""),
        os.environ.get("TRELLO_TOKEN", ""),
    )


def trello_config_available() -> bool:
    """Return True if TRELLO_API_KEY and TRELLO_TOKEN are both set."""
    key, token = _get_credentials()
    return bool(key and token)


def get_default_list_id() -> str:
    """
    Read TRELLO_LIST_ID from st.secrets or environment variables.
    Returns an empty string if the value is not set — callers should check
    for a truthy value before attempting to create cards.
    """
    try:
        import streamlit as st
        val = st.secrets.get("TRELLO_LIST_ID", "")
        if val:
            return val
    except Exception:
        pass
    return os.environ.get("TRELLO_LIST_ID", "")


# ── Card formatting ───────────────────────────────────────────────────────────

def format_card_description(card: dict) -> str:
    """
    Format a backlog card dict into a Trello card description.

    Mirrors the structured sections requested in the backlog card spec:
    Problem → Evidence → Why it matters → Recommended action →
    Priority score → Confidence → Acceptance criteria → Human review notes.

    All content comes from the card dict — nothing is invented here.
    """
    lines = [f"*{card.get('user_story', '')}*", ""]

    # Problem
    lines += ["**Problem**", card.get("problem", card.get("description", "")), ""]

    # Evidence — verbatim quotes only, never invented
    quotes = card.get("evidence_quotes", [])
    if quotes:
        lines += ["**Evidence**"]
        for q in quotes[:3]:
            lines.append(f'> "{q}"')
        lines.append("")

    # Why it matters
    why = card.get("why_it_matters", "")
    if why:
        lines += ["**Why it matters**", why, ""]

    # Recommended action
    action = card.get("recommended_action", "")
    if action:
        lines += ["**Recommended action**", action, ""]

    # Priority score
    score = card.get("opportunity_score", "—")
    bd_str = card.get("score_breakdown_str", "")
    lines += [f"**Priority score:** {score}/100"]
    if bd_str:
        lines.append(bd_str)
    lines.append("")

    # Confidence
    lines += [f"**Confidence:** {card.get('confidence', '—').title()}", ""]

    # Acceptance criteria
    criteria = card.get("acceptance_criteria", [])
    if criteria:
        lines += ["**Acceptance criteria**"]
        for c in criteria:
            lines.append(f"- {c}")
        lines.append("")

    # Human review notes
    notes = card.get("human_review_notes", "")
    if notes:
        lines += ["**Human review notes**", f"⚠️ {notes}", ""]

    # Metadata footer
    lines += [
        "---",
        (
            f"Effort: {card.get('estimated_effort', '?')}  |  "
            f"Owner: {card.get('recommended_owner_area', '—')}  |  "
            f"Labels: {', '.join(card.get('labels', []))}"
        ),
        "_Generated by Review2Roadmap_",
    ]
    return "\n".join(lines)


# ── TrelloClient ──────────────────────────────────────────────────────────────

class TrelloClient:
    """
    Thin wrapper around the Trello REST API.

    Credentials are resolved at construction: explicit api_key / token
    arguments take precedence over secrets / environment variables.
    All methods return structured dicts and do not raise on API errors.
    """

    def __init__(
        self,
        api_key: str | None = None,
        token:   str | None = None,
    ):
        if api_key and token:
            self._auth = {"key": api_key, "token": token}
        else:
            k, t = _get_credentials()
            self._auth = {"key": k, "token": t}

    # ── Read ──────────────────────────────────────────────────────────────────

    def get_boards(self) -> list[dict]:
        """
        Return available Trello boards for the authenticated user.
        Each item has at least 'id' and 'name'.
        On error, returns a single-item list with an 'error' key.
        """
        try:
            resp = requests.get(
                f"{_BASE}/members/me/boards",
                params={**self._auth, "fields": "id,name", "filter": "open"},
                timeout=10,
            )
            resp.raise_for_status()
            return resp.json()
        except requests.HTTPError as exc:
            return [{"error": f"HTTP {exc.response.status_code}: {exc.response.text[:200]}"}]
        except Exception as exc:
            return [{"error": str(exc)}]

    def get_lists(self, board_id: str) -> list[dict]:
        """
        Return lists for a selected board.
        Each item has at least 'id' and 'name'.
        On error, returns a single-item list with an 'error' key.
        """
        try:
            resp = requests.get(
                f"{_BASE}/boards/{board_id}/lists",
                params={**self._auth, "fields": "id,name", "filter": "open"},
                timeout=10,
            )
            resp.raise_for_status()
            return resp.json()
        except requests.HTTPError as exc:
            return [{"error": f"HTTP {exc.response.status_code}: {exc.response.text[:200]}"}]
        except Exception as exc:
            return [{"error": str(exc)}]

    # ── Write ─────────────────────────────────────────────────────────────────

    def create_card(
        self,
        list_id:     str,
        name:        str,
        description: str,
        labels:      list[str] | None = None,
    ) -> dict:
        """
        Create a Trello card in the selected list.

        Parameters
        ----------
        list_id     : Trello list ID (from get_lists or TRELLO_LIST_ID secret)
        name        : Card title
        description : Card body — use format_card_description() to generate this
        labels      : Optional list of label name strings (informational only;
                      Trello label IDs would be needed to apply colours)

        Returns
        -------
        {"success": True,  "url": "https://trello.com/c/...", "id": "..."}
        {"success": False, "error": "..."}
        """
        payload = {
            **self._auth,
            "name":   name,
            "desc":   description,
            "idList": list_id,
            "pos":    "bottom",
        }
        try:
            resp = requests.post(f"{_BASE}/cards", data=payload, timeout=10)
            resp.raise_for_status()
            data = resp.json()
            return {
                "success": True,
                "url":     data.get("shortUrl", ""),
                "id":      data.get("id", ""),
            }
        except requests.HTTPError as exc:
            return {
                "success": False,
                "error": f"HTTP {exc.response.status_code}: {exc.response.text[:200]}",
            }
        except Exception as exc:
            return {"success": False, "error": str(exc)}
